name: Run Tests

on:
  repository_dispatch:
    types: [gos-admin, gos-player]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          if [[ "${{ github.event.action }}" == "gos-admin" ]]; then
            echo "Running admin tests..."
            npx cypress run
          elif [[ "${{ github.event.action }}" == "gos-player" ]]; then
            echo "Running player tests..."
            npx cypress run
            
          fi
      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cypress-Test-Artifacts
          path: cypress/videos
