name: Run Tests

on:
  repository_dispatch:
    types: [automation-triggered]


jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log Event Details
      - name: Log Event Details
        run: |
          echo "Triggered by: ${{ github.event.client_payload.trigger_by }}"
          echo "Source Repo: ${{ github.event.client_payload.source_repo }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"

      # Step 2: Checkout Automation Repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run --browser chrome --headless

      # Step 5: Upload Test Artifacts
      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cypress-Test-Artifacts
          path: cypress/videos
